export const SET_CITIES: 'SET_CITIES' = 'SET_CITIES';
export const FETCH_WEATHER_SUCCESS: 'FETCH_WEATHER_SUCCESS' =
	'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_FAILURE: 'FETCH_WEATHER_FAILURE' =
	'FETCH_WEATHER_FAILURE';
export const FETCH_WEATHER_REQUEST: 'FETCH_WEATHER_REQUEST' =
	'FETCH_WEATHER_REQUEST';
